version: '3.4'

services:
  recipebook:
    image: ${DOCKER_REGISTRY-}recipebook
    build:
      context: . # 确保这是你的 Dockerfile 所在的目录
      dockerfile: RecipeBook/Dockerfile # 确保这是 Dockerfile 的正确路径
    ports:
      - "80:80"
      - "443:443"
