version: '3.4'

services:
  recipebook:
    image: ${DOCKER_REGISTRY-}recipebook
    build:
      context: .
      dockerfile: RecipeBook/Dockerfile
    ports:
      - 5400:80
      - 5401:443
