# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  core6:
    image: core6
    build:
      context: .
      dockerfile: Core6/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 1433:1433
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
